name: Test

on:
  push:
    branches:
      - main
      - dev-1
      - dev-2
      - dev-3
      - dev-4
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: install dependencies
        run: npm ci
