name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get env
        run: |
          touch .env.production
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
        shell: bash
      - name: build application
        run: npm ci && npm run build
      - name: deploy application
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_YUMMY_B566A }}
          channelId: live
          projectId: yummy-b566a
